image: maven-3.8.6-jdk-17

stages:          # List of stages for jobs, and their order of execution
  - test
  - build

jar-package-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Maven building-packing started"
    - mvn package

unit-test-job:   # This job runs in the test stage.
  stage: test
  script:
    - echo "Running unit tests... This will take about some seconds."
    - mvn test